const char *unchecked_checkbox[] = {
// h w ncolor char per pixel
"60 60 2 1",
// color definitions
"  c None",
"o c #000",
// icon content
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                 o      ooooo     ",
"     ooooo                                ooo     ooooo     ",
"     ooooo                               ooooo    ooooo     ",
"     ooooo                              ooooooo   ooooo     ",
"     ooooo                             ooooooo    ooooo     ",
"     ooooo                            ooooooo     ooooo     ",
"     ooooo                           ooooooo      ooooo     ",
"     ooooo                          ooooooo       ooooo     ",
"     ooooo         o               ooooooo        ooooo     ",
"     ooooo       oooo             ooooooo         ooooo     ",
"     ooooo       ooooo           ooooooo          ooooo     ",
"     ooooo      ooooooo         ooooooo           ooooo     ",
"     ooooo       ooooooo       ooooooo            ooooo     ",
"     ooooo        ooooooo     ooooooo             ooooo     ",
"     ooooo         ooooooo   ooooooo              ooooo     ",
"     ooooo          ooooooo ooooooo               ooooo     ",
"     ooooo           ooooooooooooo                ooooo     ",
"     ooooo            ooooooooooo                 ooooo     ",
"     ooooo             ooooooooo                  ooooo     ",
"     ooooo              ooooooo                   ooooo     ",
"     ooooo               ooooo                    ooooo     ",
"     ooooo                ooo                     ooooo     ",
"     ooooo                 o                      ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     ooooo                                        ooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"     oooooooooooooooooooooooooooooooooooooooooooooooooo     ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "
};
